version: 2
jobs:
  bump-version:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Bump the version
          command: |
            curl https://raw.githubusercontent.com/pnikosis/semtag/master/semtag --output ../semtag
            chmod +x ../semtag
            GITMESSAGE=$(git log -1 --pretty=%B)

            shopt -s nocasematch
            KINDOFVERSION="patch"
            if [[ $GITMESSAGE =~ (#major|#minor|#patch) ]]; then
                KINDOFVERSION=${BASH_REMATCH[1]}
                KINDOFVERSION=`echo $KINDOFVERSION | tr '[:upper:]' '[:lower:]'`
                KINDOFVERSION=${KINDOFVERSION//#}
            fi

            echo $KINDOFVERSION
            ../semtag final -s $KINDOFVERSION
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Java for SonarCloud Scanner
          command: |
            apt-get update -y
            apt-get install default-jdk -y
      - run:
          name: Run SonarCloud Scanner
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-sonarscanner --version 4.4.2
            dotnet restore
            dotnet-sonarscanner begin /k:"Gaardsholt_$CIRCLE_PROJECT_REPONAME" /n:"$CIRCLE_PROJECT_REPONAME" /d:sonar.organization="gaardsholt-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR"
            dotnet msbuild /t:Rebuild
            dotnet-sonarscanner end /d:sonar.login="$SONAR"
  build:
    docker:
      - image: docker:18.05.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Build and push docker image
          command: |
              docker build -t gaardsholt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 ./$CIRCLE_PROJECT_REPONAME
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bump-version:
          filters:
            branches:
              only: master
            tags:
              ignore: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - test:
          filters:
            branches:
              only: master
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
          requires:
            - test