version: 2.1

executors:
  docker:
    docker:
      - image: docker:18.05.0-ce
  dotnet:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    

commands:
  docker-build:
    steps:
      - run:
          name: "Docker: Building"
          command: docker build -t gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:1} -t gaardsholt/$CIRCLE_PROJECT_REPONAME:latest ./$CIRCLE_PROJECT_REPONAME
  docker-login:
    steps:
      - run:
          name: "Docker: Logging in"
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  docker-push:
    steps:
      - run:
          name: "Docker: Push"
          command: |
            docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:1}
            docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:latest

jobs:
  test:
    executor: docker
    steps:
      - checkout
      - run:
          name: Install Java for SonarCloud Scanner
          command: |
            apt-get update -y
            apt-get install default-jdk -y
      - run:
          name: Run SonarCloud Scanner
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-sonarscanner --version 4.4.2
            dotnet restore
            dotnet-sonarscanner begin /k:"Gaardsholt_$CIRCLE_PROJECT_REPONAME" /n:"$CIRCLE_PROJECT_REPONAME" /d:sonar.organization="gaardsholt-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR"
            dotnet msbuild /t:Rebuild
            dotnet-sonarscanner end /d:sonar.login="$SONAR"
  build-docker:
    executor: docker
    steps:
      - setup_remote_docker
      - run:
          name: Install pre-reqs
          command: |
              apk update
              apk add openssh
              apk add git
      - checkout
      - docker-build
      - docker-login

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - build-docker:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
          requires:
            - test
          post-steps:
            - docker-push

  test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - build-docker:
          filters:
            tags:
              ignore: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
          requires:
            - test
